services:
  postgres:
    image: postgres:16-alpine
    container_name: examen_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: examen_microservicios
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d examen_microservicios"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - examen_net

  backend-users:
    build: ./backend-users
    container_name: backend_users
    restart: always
    ports:
      - "3001:3001"
    environment:
      PORT: 3001
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: admin
      DB_PASSWORD: admin123
      DB_NAME: examen_microservicios
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - examen_net

  frontend-users:
    build: ./frontend-users
    container_name: frontend_users
    restart: always
    ports:
      - "5171:5171"
    depends_on:
      - backend-users
    networks:
      - examen_net

  backend-products:
    build: ./backend-products
    container_name: backend_products
    restart: always
    ports:
      - "3002:3002"
    environment:
      PORT: 3002
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: admin
      DB_PASSWORD: admin123
      DB_NAME: examen_microservicios
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - examen_net

  frontend-products:
    build: ./frontend-products
    container_name: frontend_products
    restart: always
    ports:
      - "5172:5172"
    depends_on:
      - backend-products
    networks:
      - examen_net

  backend-orders:
    build: ./backend-orders
    container_name: backend_orders
    restart: always
    ports:
      - "3003:3003"
    environment:
      PORT: 3003
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: admin
      DB_PASSWORD: admin123
      DB_NAME: examen_microservicios
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - examen_net

  frontend-orders:
    build: ./frontend-orders
    container_name: frontend_orders
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - backend-orders
    networks:
      - examen_net

volumes:
  postgres_data:

networks:
  examen_net:
    driver: bridge